//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SierraBravo.Xbox.Repositories.XboxVotingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xbox2.sierrabravo.net/", ConfigurationName="XboxVotingService.XboxVotingServiceSoap")]
    public interface XboxVotingServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xbox2.sierrabravo.net/SetGotIt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SetGotIt(int id, string apiKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xbox2.sierrabravo.net/AddVote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddVote(int id, string apiKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xbox2.sierrabravo.net/CheckKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CheckKey(string apiKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xbox2.sierrabravo.net/AddGame", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddGame(string title, string apiKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xbox2.sierrabravo.net/GetGames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        XboxGame[] GetGames(string apiKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xbox2.sierrabravo.net/ClearGames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ClearGames(string apiKey);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xbox2.sierrabravo.net/")]
    public partial class XboxGame : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string ipAddressField;
        
        private string keyField;
        
        private string statusField;
        
        private string titleField;
        
        private int votesField;
        
        private System.DateTime voteTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IpAddress {
            get {
                return this.ipAddressField;
            }
            set {
                this.ipAddressField = value;
                this.RaisePropertyChanged("IpAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Votes {
            get {
                return this.votesField;
            }
            set {
                this.votesField = value;
                this.RaisePropertyChanged("Votes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime VoteTime {
            get {
                return this.voteTimeField;
            }
            set {
                this.voteTimeField = value;
                this.RaisePropertyChanged("VoteTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface XboxVotingServiceSoapChannel : SierraBravo.Xbox.Repositories.XboxVotingService.XboxVotingServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XboxVotingServiceSoapClient : System.ServiceModel.ClientBase<SierraBravo.Xbox.Repositories.XboxVotingService.XboxVotingServiceSoap>, SierraBravo.Xbox.Repositories.XboxVotingService.XboxVotingServiceSoap {
        
        public XboxVotingServiceSoapClient() {
        }
        
        public XboxVotingServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XboxVotingServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XboxVotingServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XboxVotingServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SetGotIt(int id, string apiKey) {
            return base.Channel.SetGotIt(id, apiKey);
        }
        
        public bool AddVote(int id, string apiKey) {
            return base.Channel.AddVote(id, apiKey);
        }
        
        public bool CheckKey(string apiKey) {
            return base.Channel.CheckKey(apiKey);
        }
        
        public bool AddGame(string title, string apiKey) {
            return base.Channel.AddGame(title, apiKey);
        }
        
        public XboxGame[] GetGames(string apiKey) {
            return base.Channel.GetGames(apiKey);
        }
        
        public bool ClearGames(string apiKey) {
            return base.Channel.ClearGames(apiKey);
        }
    }
}
